title       : "DS-Homebrew Wiki"
description : "Wikis for DS-Homebrew projects"
repo        : "DS-Homebrew/wiki"
color       : "#072f4f"
image       : "https://avatars1.githubusercontent.com/u/46971470?s=200&v=4"

collections_dir: pages

defaults:
  - scope:
      path: ""
    values:
      layout: wiki
  - scope:
      path: assets/js
    values:
      layout: null

collections:
  en-US:
    output: true
    permalink: /:path:output_ext
  ic-IC:
    output: true
  da-DK:
    output: true
  de-DE:
    output: true
  es-ES:
    output: true
  fr-FR:
    output: true
  he-IL:
    output: true
  hu-HU:
    output: true
  id-ID:
    output: true
  it-IT:
    output: true
  ja-JP:
    output: true
  ko-KR:
    output: true
  nl-NL:
    output: true
  no-NO:
    output: true
  pl-PL:
    output: true
  pt-PT:
    output: true
  ru-RU:
    output: true
  sv-SE:
    output: true
  tr-TR:
    output: true
  uk-UA:
    output: true
  zh-CN:
    output: true
  zh-TW:
    output: true
