title       : "DS-Homebrew Wiki"
description : "Wikis for DS-Homebrew projects"
repo        : "DS-Homebrew/wiki"
color       : "#072f4f"
image       : "https://avatars1.githubusercontent.com/u/46971470?s=200&v=4"

collections_dir: pages

collections:
  en-US:
    output: true
    permalink: /:path:output_ext
  ic-IC:
    output: true
  da-DK:
    output: true
  de-DE:
    output: true
  es-ES:
    output: true
  fr-FR:
    output: true
  he-IL:
    output: true
  hu-HU:
    output: true
  it-IT:
    output: true
  ja-JP:
    output: true
  ko-KR:
    output: true
  no-NO:
    output: true
  pl-PL:
    output: true
  pt-PT:
    output: true
  ru-RU:
    output: true
  sv-SE:
    output: true
  tr-TR:
    output: true
  uk-UA:
    output: true
  zh-CN:
    output: true
  zh-TW:
    output: true

lang-names:
  da-DK: Dansk
  de-DE: Deutsch
  en-US: English
  es-ES: Español
  fr-FR: Français
  he-IL: עברית
  hu-HU: Magyar
  it-IT: Italiano
  ja-JP: 日本語
  ko-KR: 한국어
  no-NO: Norsk bokmål
  pl-PL: Polski
  pt-PT: Português
  ru-RU: Русский
  sv-SE: Svenska
  tr-TR: Türkçe
  uk-UA: Українська
  zh-CN: 中文 (简体)
  zh-TW: 中文 (繁體)

rtl: [he-IL]