name: Deploy site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doc-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Run Jekyll
        # Build the site using Jekyll
        run: JEKYLL_ENV=production bundle exec jekyll build

        # Copy (or touch) other needed files
        # .nojekyll: to tell GH Pages to not rebuild (lol)
      - name: Post-Jekyll build copy files
        run: touch _site/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
